### PR TITLE
615: Remove zalando-incubator Leftovers

### PR DESCRIPTION
**Pull request by netme**
Related to #615

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
`sed -r 's/-incubator//g'` ? :)

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
@maxim-tschumak then the changes will be in one big chunk :-)

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
