### PR TITLE
UseSpecificHttpStatusCodes allows PATCH to respond 204

### PR DESCRIPTION
**Pull request by roxspring**
Updates Zally in accordance with: https://github.com/zalando/restful-api-guidelines/issues/341.

Addresses #630.

### CODE REVIEW

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@netme please re-approve and merge :)

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
come on, Travis! I want to merge and finally go home

**Comment by netme** [comment]
@maxim-tschumak time to optimise our Travis build :-)

**Pull request merged**
