### PR TITLE
fix: improve downloading of the codacy-coverage-reporter (#672)

### LINKED ISSUE #672: Fix Codacy Reporting
For now, Codacy fails sometimes with this error:

```
The command "wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)" failed and exited with 4 during .
```

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #672.

### CODE REVIEW

**Comment by mfellner** [comment]
We should directly download a version of the reporter instead.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by mfellner** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
