### PR TITLE
[WIP] Codacy / Detekt Configuration

### PR DESCRIPTION
**Pull request by roxspring**

### CODE REVIEW

**Comment by roxspring** [comment]
Grrr. I hate Codacy. Now I can't generate errors in order to test configuration fixes. Arrggghhh!!!!!

**Comment by maxim-tschumak** [comment]
I've deactivated codecov webhook - it was annoying. Should I re-activate it so that you can test the custom config?

**Comment by roxspring** [comment]
LOL clearly we both hit breaking point around the same time and reached for different solutions!

I'm not sure what the right answer is really - on one hand, static analysis can help identify some stupid mistakes and keeps us honest around coding standards - on the other hand, it's very annoying to have all these nitpicky complaints only pointed out at CI time after a PR has been prepared.

I'm tempted to try running Detekt direct from the gradle build so that complaints can be picked up and addressed earlier - but I don't know how much this will slow the build down.

**Comment by maxim-tschumak** [comment]
Here is the issue regarding improving the code coverage tooling: #167
I like the idea of integrating a code quality tool into the build process - let's give it a try!

**Pull request closed without merging**
