### PR TITLE
Fix: #1086. Add orEmpty() if scopes are empty

### LINKED ISSUE #1086: Rule SecureAllEndpointsWithScopesRuleTest throws NPE when providing OpenAPI with no scopes defined
I stumbled across an issue when testing an OpenAPI specification without having OAuth2 scopes defined properly. I got a 500 and a NullPointerException within the server application.

```
Cannot submit file for linting. HTTP Status: 500, Response: {"title":"Internal Server Error","status":500,"detail":"check invocation failed: id=105 title=Secure All Endpoints With Scopes checkName=checkOperationsAreScoped reason=java.lang.NullPointerException"}
```

```
java.lang.RuntimeException: check invocation failed: id=105 title=Secure All Endpoints With Scopes checkName=checkOperationsAreScoped reason=java.lang.NullPointerException
        at de.zalando.zally.rule.RulesValidator.invoke(RulesValidator.kt:63) ~[main/:na]
        at de.zalando.zally.rule.RulesValidator.validate(RulesValidator.kt:40) ~[main/:na]
        at de.zalando.zally.rule.CompositeRulesValidator.validate(CompositeRulesValidator.kt:13) ~[main/:na]
        at de.zalando.zally.apireview.ApiViolationsController.validate(ApiViolationsController.kt:47) ~[main/:na]
        ... 127 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at de.zalando.zally.rule.RulesValidator.invoke(RulesValidator.kt:61) ~[main/:na]
        ... 97 common frames omitted
Caused by: java.lang.NullPointerException: null
        at de.zalando.zally.rule.zalando.SecureAllEndpointsWithScopesRule.defined(SecureAllEndpointsWithScopesRule.kt:76) ~[main/:na]
        at de.zalando.zally.rule.zalando.SecureAllEndpointsWithScopesRule.checkOperationsAreScoped(SecureAllEndpointsWithScopesRule.kt:49) ~[main/:na]
        ... 102 common frames omitted
```

I will provide a fix and test for this issue.

### PR DESCRIPTION
**Pull request by fdomig**
Feel free to merge this fix.

Fixes #1086

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by fdomig** [comment]
Any chance of merging this soon?

**Comment by zeitlinger** [comment]
:+1:

**Comment by zeitlinger** [comment]
@tkrop please approve

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
