### PR TITLE
Update React to 16

### LINKED ISSUE #613: Update to React 16
React 16 is out and with better performance.

### PR DESCRIPTION
**Pull request by ruiaraujo**
Also improved the webpack config to generate proper dev and prod bundles.

Closes #613 #614

### CODE REVIEW

**Comment by netme** [comment]
@ruiaraujo could you please add a GH issue for that?

**Comment by rbarilani** [comment]
👍

**Comment by ruiaraujo** [comment]
👍

**Comment by ruiaraujo** [comment]
the codeacy check looks broken.

**Comment by rbarilani** [comment]
@ruiaraujo I tried to re-trigger the analysis but it didn't work! I don't have admin rights on that codacy project... maybe you have...

**Comment by ruiaraujo** [comment]
@netme Can you help here?

**Comment by netme** [comment]
@ruiaraujo I will take a look. Could you please try meanwhile:

```
git commit --amend
git push --force-with-lease origin BRANCH
```

Might help

**Comment by ruiaraujo** [comment]
@netme Did not help.

**Comment by ruiaraujo** [comment]
👍

**Comment by netme** [comment]
@ru

**Comment by netme** [comment]
I will check once I will reach my laptop :-) Sorry hard to do it from mobile

**Comment by netme** [comment]
Updated the branch, let's see what Codacy will report

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
@ruiaraujo seems to be Codacy failing on such a big diff. Could you please approve it again and I'll merge it.

**Comment by netme** [comment]
👍

**Comment by ruiaraujo** [comment]
👍

**Comment by ruiaraujo** [comment]
👍

**Comment by netme** [comment]
👍

**Pull request merged**
