### PR TITLE
feat(server): add NumericPropertyBoundsRule #944

### LINKED ISSUE #944: NumericPropertyBoundsRule
New rule proposal: ZallyRuleSet S006 SHOULD Define bounds for numeric properties

Creates violations if specifications include schemas numeric properties but without minimum or maximum.

PR coming shortly.

### PR DESCRIPTION
**Pull request by roxspring**
Closes #944

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
@roxspring can you please correct the commit message for 01c3609.

**Comment by tkrop** [comment]
@roxspring can you fix the `klint` problems:
```
/home/travis/build/zalando/zally/server/src/test/java/de/zalando/zally/rule/zally/NumericPropertyBoundsRuleTest.kt:4:1: Unused import
/home/travis/build/zalando/zally/server/src/test/java/de/zalando/zally/rule/zally/NumericPropertyBoundsRuleTest.kt:6:1: Unused import
/home/travis/build/zalando/zally/server/src/test/java/de/zalando/zally/rule/zally/NumericPropertyBoundsRuleTest.kt:8:1: Unused import
```
I assume these are consequences of the latest kotlin update in our last PR.

**Comment by zeitlinger** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
