### PR TITLE
fix(server): Use correct description for Http Header Pascal Case rule. (Fixes #906)

### LINKED ISSUE #906: Incorrect description for PascalCaseHttpHeadersRule.
An incorrect description is used in PascalCaseHttpHeadersRule. Has been fixed with PR #905.

### PR DESCRIPTION
**Pull request by ech0s7r**
Fixes issue #906

### CODE REVIEW

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@ech0s7r I've created a new PR based on a copy of your branch since our CD pipeline doesn't allow PRs from extern repositories. See #912

**Pull request closed without merging**
