### PR TITLE
NullPointerExceptionTest

### PR DESCRIPTION
**Pull request by roxspring**
- Added `NullPointerExceptionTest` running purposefully null ridden specs against all rules
  - Based on some full-featured specs, progressively pruned
- Fixed various NullPointerExceptions

#832

### CODE REVIEW

**Comment by ddufourboivin-zalando** [comment]
Might be a rhetorical question ... but was there no other way to fix that than making that much stuff nullable...?

**Comment by roxspring** [comment]
> Might be a rhetorical question ... but was there no other way to fix that than making that much stuff nullable...?

Arguably it was already nullable, Kotlin just didn't realise it.

Clearly there is an alternate approach where we post-process the model and replace nulls with "empty values", either by handcoding a crawl of the model or by enhancing/copying the `ReverseAst` to do so automatically. For many cases an "empty value" object exists which could be used e.g. `PathItem`, `ApiResponses` but I'm not sure that always makes sense - e.g. is it acceptable to replace null Strings with ""? What about null Booleans?

**Comment by ddufourboivin-zalando** [comment]
Checking for _empty value_ or for _null_ both require an extra effort. At that point, I am OK with using nullability (which is nicely supported in Kotlin). Thanks for the explanation.

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
