### PR TITLE
553: API Title Must be Set

### LINKED ISSUE #553: New Check: API Title Must be Set
**Description:** API Title in the OpenAPI definition must be set. This is related to [101](http://zalando.github.io/restful-api-guidelines/#101)

**Acceptance Criteria**
- New Zally check validates if `info.title` is set and is not empty (there is no minimal length)
- New check is implemented and tested

### PR DESCRIPTION
**Pull request by netme**
Closes #553 

Provides only some refactoring. Found out that API title is already checked as a part of OpenAPI Specification check.

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
Fixed issues found by `ktlint`

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Pull request merged**
