### PR TITLE
Fix #1079. Build webapp inside a java container.

### LINKED ISSUE #1079: Zally server Dockerfile fails if ./build-and-run.sh hasn't been invoked first
On a fresh clone of Zally, I can't run docker-compose without first running ./build-and-run.sh.  The reason is that the Dockerfile for zally server tries to copy all of the /build files in the server directory to the container image, but if you don't run ./build-and-run.sh first then the /build folder doesn't exist.  I would expect either the documentation to state that you must build the server first, or for the Dockerfile to handle the build for the user.

```
~/zally$ podman-compose build
podman build -t zally_server -f ./server/Dockerfile ./server
STEP 1: FROM registry.opensource.zalan.do/stups/openjdk:latest
STEP 2: MAINTAINER "http://zalando.github.io/"
--> Using cache 05a4de6e4e50e3d13d11b5b7d7b402fb264c08e88f560788a840bc65a4f9c7b4
STEP 3: COPY src/main/resources/api/zally-api.yaml /zalando-apis/zally-api.yaml
--> Using cache 2124c6689b6b16a8b372f359c942a05d54e0567b1c645155876984cfeb36d53a
STEP 4: COPY build/libs/zally.jar /
Error: error dry-running "COPY build/libs/zally.jar /": no files found matching "/home/colinmckibben/Documents/fireeye/github/zally/server/build/libs/zally.jar": no such file or directory
125
podman build -t zally_web-ui -f ./web-ui/Dockerfile ./web-ui
STEP 1: FROM node:12
STEP 2: MAINTAINER "http://zalando.github.io/"
--> Using cache 7c9bc12cdfc824b2d08f0a76b376321ccac615ea55ab514e1f1b2a4f57e5d147
STEP 3: COPY package.json ./
--> Using cache 390faf236aed86c56905303c0f32b425027772a7df96862875a8c3553cceba90
STEP 4: COPY yarn.lock ./
--> Using cache 9d174130404fd1a08c07e6ae5c7487b0466989d9f1710fe2b1cb6f4b5bcbcb5e
STEP 5: RUN npm install -g yarn
--> Using cache 7a5a1bcefeb2c944670e39b6ad14c01b09f08020a3a08339dab1b9ebbd1a9d7b
STEP 6: RUN yarn --production
--> Using cache d0d8d0e4fba9ddd76e088a6da781a3eb6e55f82b39170623b92c4fb69383ce14
STEP 7: COPY src ./src
--> Using cache 648c2e0eac41144dd7c5701f2508957a3917a0f60486fc0167f98658b05afc1e
STEP 8: COPY server.js ./
--> Using cache 0a0d3916d183baec4c1be19286e95c107e7a39514af5d8f2fad8def75cb34128
STEP 9: EXPOSE 3000
--> Using cache c33d032f714efe92a868fdd59dcc276290eff08408f8dd03db966011575496f7
STEP 10: CMD ["node", "server.js"]
--> Using cache d2572b950ac7b153edd762aff260ccf601fdd7eb97807c9686192aa0c2076b3f
STEP 11: COMMIT zally_web-ui
d2572b950ac7b153edd762aff260ccf601fdd7eb97807c9686192aa0c2076b3f
0
```

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

Builds the gradle application inside a container and avoids running or installing
anything inside the docker machine.

## It's done

Via a multi-stage build. https://docs.docker.com/develop/develop-images/multistage-build/

### CODE REVIEW

**Comment by ioggstream** [comment]
> drops the build-time dependency on Java + Gradle

Done relatively to the server component. The github integration part should be managed separately,
and I suggest doing it in a separate PR.

**Comment by vadeg** [comment]
Thank you for PR. 

The only thing which will be installed on docker machine will be JVM. The project is written in Kotlin  and having JVM on a host machine is totally fine. Also it required by different IDE. What is the point of using docker image then?

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
👍

**Pull request merged**
