### PR TITLE
#650 omit json object response check for non-json endpoints

### LINKED ISSUE #650: Zally reports violation of rule #110 for endpoints returning binary data
I have endpoint which returns file content as binary
```yaml
  "/reports/{report-id}":
    get:
      produces:
        - application/pdf
      responses:
        '200':
          description: Return report as a PDF file
          schema:
            type: file
```
Zally reports violation: 
```
MUST – Response As JSON Object
Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
Rule: https://zalando.github.io/restful-api-guidelines/#110
```

But in fact this is totally valid according to [rule 168](https://zalando.github.io/restful-api-guidelines/#168)

### PR DESCRIPTION
**Pull request by mkulak**
Closes #650

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by mkulak** [comment]
This is coverage from Intellij: Idea coverage

**Comment by mkulak** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
