### PR TITLE
625 Introduce Package Manager for CLI

### LINKED ISSUE #625: Introduce package manager for GO CLI
```
As a developer
I want to make sure that my CLI dependencies have proper versions
So that I will be sure that my code compiles properly
```

## Steps:
- Introduce a package manager
- Use latest package versions
- Update readme
- Update CI pipelines

## Options to consider:
- GLIDE
- GoDep

### PR DESCRIPTION
**Pull request by netme**
Closes #625

### CODE REVIEW

**Comment by netme** [comment]
@maxim-tschumak could you please take a look once you'll have a moment?

**Comment by maxim-tschumak** [comment]
Great!

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Pull request merged**
