### PR TITLE
docs: add documentation for building under Windows

### PR DESCRIPTION
**Pull request by roxspring**
Adds documentation as commented in #919.

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@roxspring please add issue reference to the commit message

**Comment by roxspring** [comment]
Huh. You'd think I'd know that by now :)

**Comment by maxim-tschumak** [comment]
I'll try to get some time next week to improve the CI/CD setup - please ignore CDP error messages

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
@roxspring if you like you can add a shell/bash script for this steps and simplify the documentation.

**Comment by tkrop** [comment]
:+1:

**Comment by roxspring** [comment]
I'm sure it could be more scripted but is it worth it?

- Apart from the `build-and-run.sh` then everything else is a one-off step to get the environment right.

- There'd still be a number of prereq steps just to _get_ the script:

  ```
  sudo apt-get update -y && sudo apt-get install -y git
  cd /mnt/c
  git clone https://github.com/zalando/zally
  cd zally
  ./setup-debian-environment.sh
  ```
  
- We could host an online script and assume/paramterize the `C:\zally` location, but even then curl needs to be manually installed into the environment first:

  ```
  sudo apt-get update -y && sudo apt-get install -y curl
  curl -sL https://raw.githubusercontent.com/zalando/zally/master/setup-debian-environment.sh | sudo -E bash -
  ```

Even if we do script it up I'm tempted to wait until somebody else confirms that the steps work for them and that non of this is peculiar to my Windows setup in the first place!

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
