### PR TITLE
696 Add Support for Plain Text Format

### LINKED ISSUE #696: Add support for text format in Zally CLI
Currently we are supporting 2 output formats:
- pretty (plain text with colors)
- markdown

Add support for `text` format (same behaviour as `pretty`, but without using ascii colors).

### PR DESCRIPTION
**Pull request by netme**
Closes #696 

### How to try it out:
- Run server
- Build it
- Run the following commands:
    ```bash
    ./zally lint --format=text ../../server/src/test/resources/fixtures/api_spp.json
    ```

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
great!

**Comment by maxim-tschumak** [comment]
:)

**Comment by netme** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
:+1:

**Pull request merged**
