### PR TITLE
Fix typo in IdentifyResourcesViaPathSegments title

### PR DESCRIPTION
**Pull request by fehmicansaglam**
fixes #1027.

### CODE REVIEW

**Comment by tkrop** [comment]
@fehmicansaglam can you fix the PR by adding `(#1027)` to the commit message, so that I can merge this PR?

**Comment by fehmicansaglam** [comment]
@tkrop done.

**Comment by tkrop** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:

**Pull request merged**
