### PR TITLE
Drop Spring dependencies from rule loading & processing

### LINKED ISSUE #122: Consider using JDK-Standard 'ServiceLoader' instead of Spring
... for loading rules into validator.

Hi Zally-Team, I would like you to consider using the ['ServiceLoader'-Feature](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html) to load existing rules into the validator. Sure, I don't know what you plan for the future with Zally and how the Rules-interface will evolve in the future. From what I have seen so far, the ServiceLoader provided by the JDK can replace the existing mechanism to load the rules and the validator itself does not depend anymore on spring.

Removing the dependency to spring could make the validator more interesting for other projects. As an example [swagger-codegen-tooling](https://github.com/zalando-stups/swagger-codegen-tooling) comes into my mind. It would be a nice feature to validate the swagger.yaml before generating code.
Also for other integrations (Gradle-plugin) it would make sense to provide a validator with minimal dependencies.

Please have a look into the 'serviceloader'-branch to see how the 'ServiceLoader' can be used.

Regards
Jörg

### PR DESCRIPTION
**Pull request by roxspring**
- Removed some Spring dependencies in preparation for spring-free core subproject #560:
  - RulesValidators
  - Remove `SwaggerRulesValidator` which was no longer being used for production.
  - RuleSet implementations
- Rule instantiation is now driven ServiceLoader style without dependency on Spring
  - Added Kotlin annotation processor `RuleProcessor` to produce resources based on `@Rule` annotations
  - Added `RuleManager` companion object with factory methods to process resources and load the instances.
  - Closes #122

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by zeitlinger** [comment]
@roxspring always a pleasure to read your Kotlin code - I'll recommend it to our Kotlin guild!

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
@roxspring thanks for the contribution.

**Pull request merged**
