### PR TITLE
refactor: improve docker environment

### PR DESCRIPTION
**Pull request by ABGEO**
## web-ui
- Fix heathcheck by installing `curl`
- Move the build process to the docker container (no local Yarn needed anymore)

## server
- Use multi-stage docker build to generate server `.jar`

## Docker Compose
- Fix formatting
- Add volume for `postgres` container to preserve the state
- Improve caching

### CODE REVIEW

**Comment by ABGEO** [comment]
ping

**Comment by chamoda** [comment]
If anyone get the error  `ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ea1c9a0c-1d43-4ea5-9790-ed1882c85fce::zarskmsx0awdlxwwmljsqcv1u: "/zally-server/build/libs/zally-server.jar": not found` on main branch `docker-compose up`, this PR also fix that issue.

**Comment by tkrop** [comment]
@ABGEO Sorry that it took so long. Thank you for your contribution. I was a bit hesitant to merge this, because we intend to remove the Web UI, since it is unmaintained, heavily outdated, and has many vulnerabilities.

**Comment by ktsypkina** [comment]
👍

**Comment by ktsypkina** [comment]
tested changes, works on my local as well 👍

**Pull request merged**
