### PR TITLE
Moved shared HttpHeadersRule code to core package

### PR DESCRIPTION
**Pull request by roxspring**
Moved shared `HttpHeadersRule` code to core package used by both zally and zalando sub-packages, rather than have a dependency between the ruleset sub-packages.

Tidying up package dependencies ahead of #560.

### CODE REVIEW

**Comment by roxspring** [comment]
Anybody able to explain the ci failure? Haven't been able to reproduce and understand locally!?

**Comment by maxim-tschumak** [comment]
@roxspring I couldn't reproduce the error either. Retriggering Travis CI helped...

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
Let's me update branch and check again if there is any CI issue.

**Comment by netme** [comment]
👍

**Comment by netme** [comment]
The build worked, @maxim-tschumak , could you please re-approve?

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
