### PR TITLE
Make CDP builds run in parallel

### LINKED ISSUE #1279: Make CDP builds run in parallel
Github Actions builds all artefacts within `6 minutes while CDP builds all artefacts within ~14 minutes. 
Make CDP builds parallel for server, cli, web and github integration.

### PR DESCRIPTION
**Pull request by vadeg**
* Enable concurrent steps
* Enable dependencies caching
* Move docker images build into CDP pipeline and remove build bash script
* ~Add test reporting~ (moved to a separate ticket - #1298)

Fixes #1279

### CODE REVIEW

**Comment by vadeg** [comment]
There is a bug with an infrastructure tool. Waiting for a reply from infrastructure team.

**Comment by vadeg** [comment]
Depends on #1295

**Comment by tkrop** [comment]
Sorry, for not reviewing this so long.

I still would like to have small scripts or a `Makefile` with targets to execute each step also on a local machine for testing. However, I will approve and leave it for a later change.

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
@tkrop there is `build-and-run.sh` which does the same.

**Pull request merged**
