### PR TITLE
Add index on `api_review_id` column in `rule_violations` table.

### LINKED ISSUE #1235: Permalink in Zally UI is very slow that it appears somethimes broken.
This issue a placeholder for an Zalando internal issue. Please have a look at [developer-console/issues#595](https://github.bus.zalan.do/pitchfork/developer-console/issues/595) for details.

### PR DESCRIPTION
**Pull request by vadeg**
Fixes #1235

### CODE REVIEW

**Comment by tkrop** [comment]
:+

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
👍

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
