### PR TITLE
Fixing Travis CI Build

### LINKED ISSUE #663: Fix TravisCI Build
Triggered by https://github.com/zalando/zally/pull/657#issuecomment-370943200.

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #663.

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:-1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
:+1:

**Pull request merged**
