### PR TITLE
Move server to its own module and clean up dependencies

### PR DESCRIPTION
**Pull request by gsdatta**
Reopening #1114

### CODE REVIEW

**Comment by roxspring** [comment]
Thanks for the contribution and the fresh pull request!

Assuming this is a straight rebase then my review for the [pull request I accidentally closed](https://github.com/zalando/zally/pull/1114#pullrequestreview-350425626) should contain some further options to consider, along with the following which I think will be necessary:

- run `./gradlew ktlintFormat` - I built your branch locally and it failed the `ktlintCheck` - also the reason Travis CI is unhappy.
- Amend the commit to include `#560` in the message - the reason zapper/commit/message is unhappy.
- `server/Dockerfile` currently picks up `build/libs/zally.jar` but I think that'll be an empty jar now so I presume that it'll need to pick up `zally-server/build/libs/zally-server.jar` instead.

**Comment by tkrop** [comment]
@gsdatta You can see the failure in [Line 2895](https://travis-ci.org/zalando/zally/builds/643568994#L2895) and the reason probably in [Line 2875](https://travis-ci.org/zalando/zally/builds/643568994#L2875).

**Comment by tkrop** [comment]
@gsdatta another thing: please stick to the format of commit messages. We are following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) message format loosely, by by using a short version that is just using the first line adding the issue id to the end.

And thanks for the PR advancing the project.

**Comment by gsdatta** [comment]
Thanks all for the reviews! I should have these changes up soon

**Comment by gsdatta** [comment]
@tkrop sorry for the late turnaround, finally got a chance to make the changes - ready for another review. Thanks!

**Comment by tkrop** [comment]
Thanks for the contribution. Have just seen it and will have a look soon.

**Comment by zeitlinger** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
