### PR TITLE
Checks can now process x-zally-ignore against arbitrary locations in the definition

### PR DESCRIPTION
**Pull request by roxspring**
- Check methods now optionally take a SwaggerIgnoreExtension parameter which can be used to process the `x-zally-ignore` anywhere a vendor extension is permitted.
- LimitNumberOfSubresourcesRule modified as it was the example mentioned in #446 

For example the following will only process paths which should not be ignored:
```
@Check(severity = Severity.SHOULD)
fun validate(swagger: Swagger, ignore: SwaggerIgnoreExtension): Violation? {
    val paths = swagger.paths.orEmpty()
        .filterValues { ignore.accepts(it.vendorExtensions) }
```

### CODE REVIEW

**Comment by roxspring** [comment]
Not quite sure what's breaking the build. Unit tests and integration tests seem to be fine. Looks to be something in the UI integration tests that's broken!? Will take a closer look.

**Comment by roxspring** [comment]
I'm unable to make sense of the 3 web-ui test failures. I do see 2 web-ui failures when running the tests locally, but that's the case on this branch or master. @netme, @maxim-tschumak are either of you able to help me understand the problem?

**Comment by netme** [comment]
@roxspring , seems to be the endpoint returns 500 errors:

```
 FAIL  src/server/__tests__/integration.test.js
  ● zally-web-ui standalone › GET / › endpoint should respond as expected
    expected 200 "OK", got 500 "Internal Server Error"
      
      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:266:12)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:171:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at Server.emit (events.js:208:7)
      at emitCloseNT (net.js:1655:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  ● zally-web-ui mount › GET /linter › endpoint should respond as expected
    expected 200 "OK", got 500 "Internal Server Error"
      
      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:266:12)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:171:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at Server.emit (events.js:208:7)
      at emitCloseNT (net.js:1655:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by netme** [comment]
Let me create a dummy PR to check the `web-ui` build status.

**Comment by netme** [comment]
Let's check #660

**Comment by netme** [comment]
Yes, seems to be the same issue. @maxim-tschumak , @ruiaraujo could you please follow up on this?

**Comment by netme** [comment]
Link to the build from almost clean master: https://travis-ci.org/zalando/zally/builds/350043225

**Comment by roxspring** [comment]
Looks like that failed in the same way and gets my changes off the hook :)

Puzzled by the "/" and "/linter" endpoints returning 500s... as far as I'm aware neither endpoint exists to return anything!?

**Comment by maxim-tschumak** [comment]
I'll check this, hopefully, this week.

**Comment by maxim-tschumak** [comment]
@netme I've switched from `npm` to `yarn` and deactivated `openAnalyzer` of the `BundleAnalyzerPlugin` (Web UI). It helped. Let's merge the fix first: https://github.com/zalando/zally/pull/664

**Comment by roxspring** [comment]
Is it really necessary to regain that 0.13% of coverage? Achieving it seems a lot of effort for little reward.

**Comment by maxim-tschumak** [comment]
We can ignore the test coverage here.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
@netme any chance of a review?

**Comment by netme** [comment]
Will do it tomorrow

**Comment by netme** [comment]
👍

**Comment by roxspring** [comment]
Are you happy to approve again and merge @maxim-tschumak ?

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
