### PR TITLE
Configure Github Actions

### LINKED ISSUE #1223: Move to Github Actions
Move Zally build process from Travis to Github Actions.

### PR DESCRIPTION
**Pull request by vadeg**
- [x] Add caching layer
- [x] Setup Codecov for test coverage reporting

Fixes #1223

### CODE REVIEW

**Comment by tkrop** [comment]
@vadeg Do you have an idea why https://github.com/zalando/zally/pull/1258#issuecomment-863514629 is showing such a reduce code coverage. It seems the lower test coverage is distributed to multiple source folders. Can you check where the build is doing things different?

**Comment by vadeg** [comment]
@tkrop the current test coverage is not properly configured. It doesn't collect reports from Zally `server` submodules. Travis takes a test coverage report from `server/build/reports/jacoco/test/jacocoTestReport.xml`. This file doesn't exist and is not generated by `jacoco`. The proper test reports are located in submodules' `build` folders.

#### Current report
old-report

#### New report
new-report

There is a new `server` folder appeared in the new report. Without this folder the coverage will be the same as in the old report.

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
@vadeg I see, so we had not covered the server before at all in the reported test coverage, which no reduces our coverage :smile:.

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
