### PR TITLE
feat: update rule creation docs with org.zalando (#1337)

### LINKED ISSUE #1337: Update the Custom Rule Creation documentation
In the documentation available at this [link](https://github.com/zalando/zally/blob/master/documentation/rule-development.md), the imports listed at this are not available in the Zally code anymore. Please update the documentation so that readers can correctly understand and work to create better documentation as per the organization.

```
import de.zalando.zally.rule.api.Check
import de.zalando.zally.rule.api.Context
import de.zalando.zally.rule.api.Rule
import de.zalando.zally.rule.api.Severity
import de.zalando.zally.rule.api.Violation
```

Thanks.

### PR DESCRIPTION
**Pull request by tkrop**
fixes #1337.

### CODE REVIEW

**Comment by tkrop** [comment]
@ePaul @vadeg need to merge #1345 first.

**Comment by vadeg** [comment]
👍

**Comment by vadeg** [comment]
@tkrop could you rebase the brach with main to retrigger build please?

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
