### PR TITLE
Upgrade Dependencies

### LINKED ISSUE #784: Upgrade to swagger-parser 2.0.2 or newer
Looked at patching https://github.com/zalando/zally/issues/765 upstream and discovered it was [already fixed](https://github.com/swagger-api/swagger-parser/commit/fc28f24204531fa13a7e69e8b8c576a0decd5bbe) a month ago but not yet released.

Once the fix is released we should upgrade to the fixed version (presumed to be swagger-parser 2.0.2) and remove the hack added in https://github.com/zalando/zally/pull/781. 

Note that 2.0.1 is also available and might be worth upgrading to, but doesn't address this particular issue. A 2.0.2 release appears to be imminent and is planned in https://github.com/swagger-api/swagger-parser/issues/780

### PR DESCRIPTION
**Pull request by roxspring**
- Upgrade swagger-parser to 2.0.2
  - Removed `DefaultContext.preConvertChecks()` and `DefaultContext.preResolveChecks()` as no longer necessary
  - Modified `SnakeCaseForQueryParamsRuleTest` so that only one test fails at a time on loading fixtures
  - Modified `snakeCaseForQueryParamsInvalidExternalRef.json` to use a sibling reference as parent directory traversal has changed and broken the test.
- Upgrade nearly everything else
  - Fix some new ktlint complaints
  - Updated Gradle wrapper config
- Not upgraded
  - de.mpg.mpi-inf:javatools [1.1 -> 2017-06-28] (not a final release)
  - io.swagger.core.v3:swagger-models [2.0.1 -> 2.0.3] (indirect dependency)
  - org.zalando:problem-spring-web [0.23.0 -> 0.24.0-RC.0] (not a final release)

Closes #784

### CODE REVIEW

**Comment by ddufourboivin-zalando** [comment]
@roxspring : Have you also checked if the pre-resolve checks (in `DefaultContext`) were also fixed by the upgrade?

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
Any chance of review today? Would be great to avoid the branches getting stale while I disappear for a week!

@ddufourboivin-zalando, @maxim-tschumak, @netme and @tkrop

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
