### PR TITLE
Add "self" as an exception for the pluralization rules

### LINKED ISSUE #1180: 'self' as pseudo-identifier in resource paths
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/603 introduces changes which are relevant to the Zally project.

### PR DESCRIPTION
**Pull request by server-may-cry**
Closes #1180

### CODE REVIEW

**Comment by server-may-cry** [comment]
:+1:

**Comment by tkrop** [comment]
@server-may-cry great. Thanks for the contribution and good that you found that.

**Comment by tkrop** [comment]
:+1:

**Review by tkrop — APPROVED** [review]

**Comment by zeitlinger** [comment]
:+1:

**Pull request merged**
