### PR TITLE
feat(server): CaseChecker has single list of allowed regexes

### LINKED ISSUE #884: Path parameter case false-positive
Zally produces this violation:
```
Path parameter 'business-partner-id' does not match snake_case ([a-z][a-z0-9]*(?:_[a-z0-9]+)*) but seems to be kebab-case
```

for the following specificaiton:
```
'/item-quantity-snapshots/{business-partner-id}':
    get:
      description: |
        Returns most recent item quantity snapshot of a given partner.
      security:
        - oauth2: [zfs-inventory.item-quantity.read]
      parameters:
        - name: business-partner-id
          in: path
          required: true
          type: string
          format: uuid
          description: |
            UUID identifing the business partner.
```

The Guideline explicitely allows such path parameter names.

### PR DESCRIPTION
**Pull request by roxspring**
Closes #884

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
@roxspring : Can you check why the CI is failing?

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍

**Pull request closed without merging**
