### PR TITLE
Allow Swagger definitions without OAuth2 scopes

### LINKED ISSUE #765: [Zally-CLI 1.1] Cannot submit file for linting. HTTP Status: 500
I've noticed that the Zally-CLI fails on missing `scopes` field in `securityDefinitions`

```
$ zally lint api-without-scopes.yaml
Cannot submit file for linting. HTTP Status: 500, Response: {"title":"Internal Server Error","status":500}
```

api-without-scopes.yaml:
```yaml
swagger: '2.0'
info:
  x-api-id: 1cc9097a-f3bd-4525-a2aa-3deb494efa4c
  x-audience: business-unit-internal
  title: Test API
  version: '0.1.0'
  description: |
      Just to reproduce a bug

schemes:
  - https

produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://identity.merchant-center.zalan.do/auth/realms/retailcore/protocol/openid-connect/auth
```

The following file doesn't produce status 500 response:
```yaml
swagger: '2.0'
info:
  x-api-id: 1cc9097a-f3bd-4525-a2aa-3deb494efa4c
  x-audience: business-unit-internal
  title: Test API
  version: '0.1.0'
  description: |
      Just to reproduce a bug

schemes:
  - https

produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://identity.merchant-center.zalan.do/auth/realms/retailcore/protocol/openid-connect/auth
    scopes:
      uid: "dsfd"
```

```sh
$ zally -v
Zally-CLI version 1.1
```

### PR DESCRIPTION
**Pull request by roxspring**
Added hack to avoid `NullPointerException` in swagger to openapi conversion code.

Closes #765

### CODE REVIEW

**Comment by ddufourboivin-zalando** [comment]
@roxspring : I am actually working on a more global fix for those situation. But you fix is simple (in a good way!) and straight to the point. I am for merging it so this is fixed ASAP. I actually am even considering applying that same logic in my solution (sometimes, simple is too obvious and I did not think of this, thanks!).

My pull request will appear before the end of the week.

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Comment by roxspring** [comment]
@ddufourboivin-zalando - if I understand correctly then your more global fix is to identify conversion failures and clearly report them as such - and so I agree that the two approaches are complementary: We should work around upstream deficiencies when known, but fall back to something comprehensible rather than propagate `NullPointerExceptions`!

**Pull request merged**
