### PR TITLE
feat(server): migrate kebab case in path segments rule to use context object to support OpenAPI 3

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Related to #714

### CODE REVIEW

**Comment by netme** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@netme thanks for reviewing! Can you please approve using the GitHub review functionality? (we use both now: Zappr and GitHub approval)

**Comment by tkrop** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍

**Pull request merged**
