### PR TITLE
Check whether yarn is installed. 

### PR DESCRIPTION
**Pull request by dirkgomez**
Check whether yarn is installed and abort if it is not.

See https://github.com/zalando/zally/issues/683

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
Great! Thank you!

Please update the commit message `Check whether yarn is installed. See #683` -> `Check whether yarn is installed (#683)`

**Comment by dirkgomez** [comment]
Updated the commit message to comply with your style guide.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
:+1:

**Pull request merged**
