### PR TITLE
Update node to version 18 (latest LTS)

### LINKED ISSUE #1418: Unable to compile and start
```
 => ERROR [zally-main-web-ui 4/6] RUN yarn --production                                                                    2.6s
------
 > [zally-main-web-ui 4/6] RUN yarn --production:
#0 1.565 yarn install v1.22.19
#0 2.468 [1/5] Validating package.json...
#0 2.495 error @zalando/zally-web-ui@0.4.0: The engine "node" is incompatible with this module. Expected version ">=17". Got "14.20.1"
#0 2.539 error Found incompatible module.
#0 2.539 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn --production]: exit code: 1
```

### LINKED ISSUE #1419: Mismatch in nodeVersion for Web-ui "Packages.json" and "Dockerfile"
Hi Zally Maintainers,

Please be advised that the web-ui has mismatch in nodeVersion for build and Dockerfile.

/web-ui/package.json ==> Requires nodeVersion 17.x or highere.

```JSON
  "engines": {
    "node": ">=17"
  },
```

/web-ui/Dockerfile ==> yarn --production will be executed on nodeVersion 14. 
```Dockerfile
FROM registry.opensource.zalan.do/library/node-14-alpine:latest

MAINTAINER "http://zalando.github.io/"

COPY package.json ./
COPY yarn.lock ./

RUN yarn --production
```

Thanks.

### PR DESCRIPTION
**Pull request by defaude**
fixes #1418, fixes #1419

### CODE REVIEW

**Comment by defaude** [comment]
Node.js just switched to Version 18 for its "active LTS".

See [the Node.js releases page](https://github.com/nodejs/release#release-schedule) for further info :)

**Comment by ddkserv** [comment]
Hi @tkrop, @zeitlinger and @vadeg, I hope you have time to review this PR that @defaude has made?
The PR should fix the ```web-ui``` problem with docker build and mismatch node version. 
Thanks.

**Comment by vadeg** [comment]
Hi @defaude and @ddkserv ,

Thank you for the PR. The build is failing with the following error:
```
yarn add v1.22.19
[1/5] Validating package.json...
error @zalando/zally-web-ui@0.4.0: The engine "node" is incompatible with this module. Expected version ">=1[8](https://github.com/zalando/zally/actions/runs/3344566060/jobs/5614010594#step:5:9)". Got "17.[9](https://github.com/zalando/zally/actions/runs/3344566060/jobs/5614010594#step:5:10).1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by defaude** [comment]
My bad - I forgot to update the GitHub Action pipeline. I've just added another commit that should hopefully fix the build again.

**Comment by vadeg** [comment]
👍

**Comment by ddkserv** [comment]
Hi @tkrop or @zeitlinger, 
We need 1 more reviewer for this PR. 
I hope you can find the time.
Thanks

**Pull request merged**
