### PR TITLE
feat(server): Removed unnecessary Violation.paths property

### LINKED ISSUE #858: Remove deprecated paths field from Violation
The `Violation` class currently allows reporting in either unstructured paths or strongly typed json pointers. Once the transition to `Context` based rules is complete in #834 then there are a few more cases that need addressing to tidy up:

- [x] `AvoidXZallyIgnoreRule` pull request #859 
- [x] `UseProblemJsonRule` pull request #860 
- [x] `ExtractBasePathRule` pull request #861
- [x] `HyphenatedHttpHeadersRule` likely addressed via #834
- [x] `NoUnusedDefinitionsRule` likely addressed via #834
- [ ] `RulesValidator`
- [ ] Remove the fields and unnecessary constructors from `Violation`

### PR DESCRIPTION
**Pull request by roxspring**
* Removed `Violation.paths` since it's no longer being used.
* `Violation.pointer` is no longer optional.

Closes #858

### CODE REVIEW

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
FYI: Adding more changes shortly to address compiler warnings and Codacy complaints.

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
