### PR TITLE
ObjectTreeReader uses swagger-parser utils rather than jackson-dataformat-yaml

### LINKED ISSUE #658: Support for Yaml anchors and references
Repeatedly my users expect to be able to use Yaml anchors and references in their API definitions. For example the following API attempts to reuse properties between a read and read-write versions of the same object, and also attempts to use a standardized id property. The online Swagger Editor and other tools appear to be perfectly happy with this:
```yaml
swagger: '2.0'
info:
  title: Things API
  description: Description of things
  version: 1.0.0
paths:
  /things:
    post:
      parameters:
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/WriteThing'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/ReadThing'
definitions:
  Idable:
    type: object
    properties: 
      id: &standard-id-property
        type: string
        format: uuid
  WriteThing:
    type: object
    properties: &thing-editable-properties
      name:
        type: string
      description:
        type: string
  ReadThing:
    type: object
    properties:
      id: *standard-id-property
      <<: *thing-editable-properties
```

But Zally rejects this with the following `UseOpenApiRule` violations:
- instance type (string) does not match any allowed primitive type (allowed: ["object"])
  - /definitions/ReadThing/properties/<<,
- instance type (string) does not match any allowed primitive type (allowed: ["object"])
  - /definitions/ReadThing/properties/id

Suspect that ultimately this will need to be fixed upstream in swagger-parser / jackson-dataformat-yaml / snakeyaml but logging the bug here since this is where the impact is.

### PR DESCRIPTION
**Pull request by roxspring**
Closes #658

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
@maxim-tschumak any idea what this is about? Looks like another CI problem unrelated to my change :(

```
$ wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
--2018-03-08 11:29:20--  http://null/
Resolving null (null)... failed: Name or service not known.
wget: unable to resolve host address ‘null’
The command "wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)" failed and exited with 4 during .
Your build has been stopped.
```

**Comment by maxim-tschumak** [comment]
@roxspring Maybe a temporary (network) issue. I'll re-trigger Travis job.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by netme** [comment]
👍

**Pull request merged**
