### PR TITLE
fix(server): run only Zalando checks per default (#957)

### LINKED ISSUE #957: Zally server should only run Zalando checks per default

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #957 

@roxspring We always tried to be consistent with the Zalando Guidelines per default. At some point, you commented out the `ignoredRules` and we didn't see that. Now, we want to switch this back. It may impact your setup, so please check that you have your own configuration.

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
> We should have a mechanism (perhaps extended syntax for ignoreRules) to ignore an entire ruleset at a time rather than have to remember to add to this list every time a non-guideline rule is added.

Agree, we will do this after the Rule Set epic is completed.

Thanks for the fast feedback!

**Comment by zeitlinger** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:

**Pull request merged**
