### PR TITLE
Improve markdown formatting on README

### LINKED ISSUE #888: Improve markdown formatting on README
Doc change suggested in #876

### PR DESCRIPTION
**Pull request by xpepper**
Closes #888

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
@xpepper Please create an issue for this PR and link it in the commit message. (this is our compliance requirement - every commit should be linked to the specification aka GitHub issue)

**Comment by ddufourboivin-zalando** [comment]
I'd approve, but please have a look at the commit messages and PR body (failing checks).

**Comment by roxspring** [comment]
Seems a shame that a minor doc change like this can be delayed over a month - doesn't seem encouraging to newcomers. Could we relax some of these zappr rules? Perhaps just for doc changes? Perhaps just temporarily?

I've created lucky issue #888. I'm hoping that @maxim-tschumak & co have the power to update the PR body to reference that number, apply updates from master, and hopefully relax the commit message rule enough to accept this PR.

Otherwise, we need to ask @xpepper to go back and amend the commit message. The change has the hallmarks of being made via the github web interface and I'm not aware of a mechanism to amend commit messages from it. So we're asking @xpepper to `git clone`, `git checkout`, `git commit --amend`, `git push --force`, which seems a lot for such a small doc change. To me this appears like we're being a little ungrateful - and I know that's not the intention!

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
