### PR TITLE
Better priming of ReverseAst

### PR DESCRIPTION
**Pull request by roxspring**
- `JsonPointers.escape(Method,Object...)` never adjusts case of the arguments
- `MethodCallRecorder.updatePointer(..)` called only on getter methods
- `ReverseAstBuilder` traverses inherited methods as well as declared ones
- `ReverseAstBuilder` traverses `getPaths` methods first so that shared repititions can overwrite the pointer for the found objects (initially implemented it with `getPaths` last and avoided overwriting but code was slightly longer and no clearer so switched to this approach)

### CODE REVIEW

**Comment by roxspring** [comment]
CI integration tests work for me locally so I'm guessing the Travis CI failure might be a network blip.

**Comment by roxspring** [comment]
Meh. Added a virtually no-op change to demonstrate that Travis CI failure was a blip and now codecov is complaining. Only options I can see to gain the coverage back are either figure out how to make `MethodCallRecorder` throw some exceptions, or add tests for some unrelated untested code.

Any chance of sucking up the 0.07% loss and reviewing anyway @maxim-tschumak / @netme (/ @ddufourboivin-zalando)?

(chasing up some aging PRs)

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by roxspring** [comment]
@maxim-tschumak @netme any hints how I can get another approval and merge?

**Comment by maxim-tschumak** [comment]
@tkrop @ddufourboivin-zalando please approve - it's already has been reviewed

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍

**Pull request merged**
