### PR TITLE
feat(server): add StringPropertyLengthBoundsRule #947

### LINKED ISSUE #947: StringPropertyLengthBoundsRule
New rule proposal: ZallyRuleSet S007 SHOULD Define bounds for lengths of string properties

Creates violations if specifications include schemas with string properties where:

- minLength is missing or negative
- maxLength is missing or negative
- minLength > maxLength

PR coming shortly.

### PR DESCRIPTION
**Pull request by roxspring**
Closes #947

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
@roxspring can you fix the `klint` problem:
```
/home/travis/build/zalando/zally/server/src/main/java/de/zalando/zally/rule/zally/StringPropertyLengthBoundsRule.kt:33:17: Line must not begin with "&&"
```

**Comment by zeitlinger** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:

**Pull request merged**
